language: go
os: osx
before_install:
- brew update && brew install hugo
install:
- rm -rf public || exit 0
script:
- hugo
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  repo: 1yzz/1yzz.github.io
  target-branch: master
  local-dir: "./public"
  on:
    branch: master
notifications:
  slack:
    secure: Z6+u65OBfXpuYDUlaFEM7WnQj+X+Zz+Jgnvm7DvqOjzJvng9mCLQPuVlFszg4yn1/zIxM0K0XCIEAWpP5e0rqpMF3NsHZFub13OjTa9CEHeaOmrtMmHQG+v42HuY0yMekCUlfA/PDOLb+RFZjTloBlrPUksWOvGQ4/4KE2UXVGF8HoZHKUM2NsYh4sNRPj9yWl3mEJZqQfynKeksdZ96i40pIoJ7CIv/WRUlTz2PRjoiLwoPlCdHSAgq1WL2zVkjRMlWerFI2mXS1jPYyPwexrQQ7oChC+Tyj0aRqDLbXzsqt9Uf2onuOiWeVIcEjBWUfcRxO+ePhTQ6tXRjxCcROiCw4deCStXNPPK+vEOgRbRJd20rXQKq9C1lKv5XI36EgTAns+U3j73VwzlzSMWCJ+Ev1cpBSzgRvUiI9usvn0kY9EzZRKg6CpSPPzSwZd+A9f8U4ejJquuPK2SHB6KlSdDuuCsgRhhYZdGgp13Iz24uULZu8nSF0K4Ct3X13TBunRBoOpf2r/mwpfaovnMtqSo0pMT0rp3j3fCkDnEve4mvjVI7SPIINj6d3qRZLwBs0wSNLtzXZ4rSCUl+n2ltAUaTuQlx8f0TasA6gc2A+n++8jJussQFuNPDOLIzIWP5ABUXA2a+07cHcSp/rYcXTlI/s8dnnhwF02MNLTD3kcQ=
