language: go
os: osx
before_install:
- brew update && brew install hugo
install:
- rm -rf public || exit 0
script:
- hugo
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  repo: 1yzz/1yzz.github.io
  target-branch: master
  local-dir: "./public"
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: i5ze7LO2Kx2KrRhIhLY11WeOcRlXNsiayHgtuzlF7ZCKm4FNW5QpOn0PjQIw20sGLfbf0OAieogH6tSr+8IxroZm2U7fge6j3aQKsSP+gzJzMVvBrT4KKHH3TNVn5O6lPx6PQWZvteuLRfmy1y7DAMNvj91H7uFvFvr19QG1/ynMQtmGGmV1DaYyw2r7KWl2OXTE272qP4ojmgcdhmKa1nldxasS9IxHLRqNxQ7dfZS4PtHC6eqpuwqhd1DMSG4w+XMdnv5eY1IH7lWSQPcS6WZ+ojLyVypiJaMGtiEc26jqKk12RmjBBpYgqGkKJes/xT8oGZ269csecSGrN4px1uLKBKo2aUQVznbou6cTR7RQ2qcjY+69SXbL34RH1gN1V3j3rDA83c1YyumnGyQgLDa/KBam0ooHgDPkR4ig3Uy5GiyNlRoL1+XRCZXAbiaDmWdIS34xTCmWqmiZiOke9K6llcNlCa+KuPQ/p7b+ljJafZzT0MqxKzElNVSyYsf+jXG/GAb0jvzjIobtHZBxw3PSO6y+++AFKpvzbKV60KhGeFokhbgvyldopOhOKpOX9TqqK/xmh/yGmknVCZQUzprmSlSBhEi1j6ImD+rvqpCeeR4E1qiwE/l0mxhvzPGCDHZ5nWdDZGdiq+64+sNe3OXxC/vyi2uz/ZdaAIb0go0=
