language: go
os: osx
before_install:
- brew update && brew install hugo
install:
- rm -rf public || exit 0
script:
- hugo
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  repo: 1yzz/1yzz.github.io
  target-branch: master
  local-dir: "./public"
  on:
    branch: master
notifications:
  slack:
    secure: bXoNHMqUr0H6ItQfQwF2+ykT12Dlvcd4zlCqwn7EvV40ApXm+s5E2avVTaMDx+6ccjeT6/TMHPMLu1Jjg2Lr9KowzZC1ah+FgNj3hMdx9Rw9tIl7n6umQO4RC+trNPuI3LFuc+W3Ky8l4YVbsU0smSxrFn/LWgiwunuTmvwkmmwbDEx1T0XbiCWwGWaX2m2gr9mO6b8JJ9oOJ2bNK3INaYZaCDzB+bwFz+LzoTvQK2kiZ/TW/nmc9iewoIAW0Nlv+Ogj+bxbF/ADnkpZhNOW3VcddFe5JnhNRyZbcrhcHRgGBeFvQV+bl8Fn317U6zkTli2JVuQ8RDQxgYcRWtA//aMIv/Z50beD4CYmJQcf+De5epjPLBrYSBgd4gqqitixqbKDCkxOSfc7ds2aHYnvGv464ALqYcH02J544YPxSe1W0YlTW8NgLvW0zAWZYK/rJxbQ4RHgnJslmhUgavadaS7uFzD4c6Fz9vFX48G7zKOsCVss3PSj0mv2r75mNQfEjwkdrO3xNsldDTILD/z6bRokUOZxjHllQXmw0r8gZc/TlMnSVg2PrDEPBYG97Zin8YG+ipw+nHf8+HMIS2JOeCFKkXF4+IMjp3UrCYV3PGbisKUZl5EPebL80no92/bPYGmEe6ZEcckP20h1HdmdIbJYtLljcAIJ7svF+GLz8F4=
