language: go
os: osx
before_install:
- brew update && brew install hugo
install:
- rm -rf public || exit 0
script:
- hugo
deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  repo: 1yzz/1yzz.github.io
  target-branch: master
  local-dir: "./public"
  on:
    branch: master
notifications:
  slack:
    secure: M47hqcQW6DnO0pEcmhDK2ZweZEK3zKbfz4b0Zf4yu0a2KV7Ry/xf4qDOviH4SRkgYFMf+2V0mNIokjspEz9BShnkeimd7Df+eRde296ycQfdzOUSFchdWaEBSBwtX1OPg5/SbVWHr+QTyDfdbFzasj3HmnH8p4AYWxzCY47Ch7h2w+SSfckMw+XbI6slzGxPzGVGcbX49cdLyuPmbsuUqxuBnsIAuIDAXu0t6GczVnDmrjw63Iw7Ue6RzP4L5OvI+Wj1+5y7b6aMJZvoBF69qD/kfWJugAeMYkFRLmDNQ+zMLpvzgMFUYuTLGc3uuuCV7yNPVCa39/Ja/xlBWg6OJ6pwZGtnHDsq5S3TI0q59UgzB8TozK/fwinaw6mfO6c+W7aNxd13YmhS5Hzbl+eOXWpATMLjH/dILa40b9G6xd1A98YKYjsSnQUCDqoWZKOr22rGOguC9/8GPjPPexMnLEs6/x6uDC38SGySxCTwi74OxloSn5F8eCZxBO3FQEBsZPkAen/xrUcXvl0TkoSVXHoX/6/cNIKx2j2UvSwqmfx+lSsA9jGVgDtleBLGGW5+WVkF0zWi+5JsRfbUARc4AneTklGs+7M9/YG9FWTTNrxQWKnXNkymFc02J7YOk3GYbxHXk/HihgmcfZqwNH6A+3Teqj1u9cWuouhp0ym2IRo=
